#ifndef BOARDS_H
#define BOARDS_H

#define LORA_SS BOARD_LORA_SS
#define LORA_RST BOARD_LORA_RST
#define LORA_DIO0 BOARD_LORA_DIO0
#define LORA_SPI_SCK BOARD_SPI_SCK
#define LORA_SPI_MOSI BOARD_SPI_MOSI
#define LORA_SPI_MISO BOARD_SPI_MISO

#endif
